// src/data/bookingsData.js
export const bookingsData = [
  {
    id: "001",
    name: "John brevis",
    date: "07/03/2025",
    departureTime: "06 : 00",
    arrivalTime: "19 : 00",
    from: "Algeries",
    to: "Launda",
    duration: "12hr",
    profileImg: "/assets/profile-1.png", // use local path
    flightIcon: "/assets/flight.png",
  },
  {
    id: "001",
    name: "John brevis",
    date: "07/03/2025",
    departureTime: "06 : 00",
    arrivalTime: "19 : 00",
    from: "Algeries",
    to: "Launda",
    duration: "12hr",
    profileImg: "/assets/profile-1.png", // use local path
    flightIcon: "/assets/flight.png",
  },
  {
    id: "001",
    name: "John brevis",
    date: "07/03/2025",
    departureTime: "06 : 00",
    arrivalTime: "19 : 00",
    from: "Algeries",
    to: "Launda",
    duration: "12hr",
    profileImg: "/assets/profile-1.png", // use local path
    flightIcon: "/assets/flight.png",
  },
  {
    id: "001",
    name: "John brevis",
    date: "07/03/2025",
    departureTime: "06 : 00",
    arrivalTime: "19 : 00",
    from: "Algeries",
    to: "Launda",
    duration: "12hr",
    profileImg: "/assets/profile-1.png", // use local path
    flightIcon: "/assets/flight.png",
  },
  {
    id: "001",
    name: "John brevis",
    date: "07/03/2025",
    departureTime: "06 : 00",
    arrivalTime: "19 : 00",
    from: "Algeries",
    to: "Launda",
    duration: "12hr",
    profileImg: "/assets/profile-1.png", // use local path
    flightIcon: "/assets/flight.png",
  },
  {
    id: "001",
    name: "John brevis",
    date: "07/03/2025",
    departureTime: "06 : 00",
    arrivalTime: "19 : 00",
    from: "Algeries",
    to: "Launda",
    duration: "12hr",
    profileImg: "/assets/profile-1.png", // use local path
    flightIcon: "/assets/flight.png",
  },
  {
    id: "001",
    name: "John brevis",
    date: "07/03/2025",
    departureTime: "06 : 00",
    arrivalTime: "19 : 00",
    from: "Algeries",
    to: "Launda",
    duration: "12hr",
    profileImg: "/assets/profile-1.png", // use local path
    flightIcon: "/assets/flight.png",
  },
  {
    id: "001",
    name: "John brevis",
    date: "07/03/2025",
    departureTime: "06 : 00",
    arrivalTime: "19 : 00",
    from: "Algeries",
    to: "Launda",
    duration: "12hr",
    profileImg: "/assets/profile-1.png", // use local path
    flightIcon: "/assets/flight.png",
  },
  {
    id: "001",
    name: "John brevis",
    date: "07/03/2025",
    departureTime: "06 : 00",
    arrivalTime: "19 : 00",
    from: "Algeries",
    to: "Launda",
    duration: "12hr",
    profileImg: "/assets/profile-1.png", // use local path
    flightIcon: "/assets/flight.png",
  },
  {
    id: "002",
    name: "Anna Marie",
    date: "08/03/2025",
    departureTime: "09 : 30",
    arrivalTime: "21 : 30",
    from: "Cairo",
    to: "Nairobi",
    duration: "12hr",
    profileImg: "/assets/profile-1.png",
    flightIcon: "/assets/flight.png",
  },
  // Add more entries as needed
];
