name: Deploy LMS Frontend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Build frontend
      run: npm run build

    - name: Ensure remote folder & fix permissions
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          echo "Creating target folder if it doesn't exist..."
          sudo mkdir -p /var/www/html/weefly_frontend
          sudo rm -rf /var/www/html/weefly_frontend/*
          sudo chown -R ${{ secrets.EC2_USERNAME }}:www-data /var/www/html/weefly_frontend
          sudo chmod -R 775 /var/www/html/weefly_frontend

    - name: Deploy to remote server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        source: "dist/*"
        target: "/var/www/html/weefly_front"
